#!/bin/bash
# Quick setup for Minimax Discord channel with existing OpenClaw

echo "🚀 Quick Setup: Minimax Discord Channel"
echo "========================================"

echo ""
echo "📋 **Step 1: Create Discord Channel**"
echo "-------------------------------------"
echo "1. Open your Discord server"
echo "2. Create new text channel: #minimax-chat"
echo "3. Set topic: 'Minimax M2.7 AI Assistant'"
echo "4. Make sure OpenClaw bot has access"

echo ""
echo "🔧 **Step 2: Check Current Configuration**"
echo "-----------------------------------------"
echo "Your current OpenClaw models:"
openclaw models list

echo ""
echo "🤖 **Step 3: Test Minimax API**"
echo "-------------------------------"
echo "Testing Minimax OpenAI-compatible API..."
cd /home/node/.openclaw/workspace/agents
python3 test-openai-compatible-minimax.py

echo ""
echo "🎯 **Step 4: Ready-to-Use Configuration**"
echo "----------------------------------------"
echo "Files created in /home/node/.openclaw/workspace:"
echo "1. minimax-discord-integration.json - Integration config"
echo "2. discord-minimax-bot.py - Standalone bot (needs token)"
echo "3. discord-minimax-channel-config.json - Channel settings"

echo ""
echo "💡 **Option A: Use Standalone Bot**"
echo "-----------------------------------"
echo "1. Get Discord bot token from: https://discord.com/developers"
echo "2. Set environment:"
echo "   export DISCORD_BOT_TOKEN='your-token'"
echo "   export OPENAI_API_KEY='sk-cp-...' (from vision/config.env)"
echo "3. Run: python3 discord-minimax-bot.py"

echo ""
echo "💡 **Option B: Integrate with OpenClaw**"
echo "----------------------------------------"
echo "1. OpenClaw already has Discord configured"
echo "2. We need to add Minimax agent binding for #minimax-chat"
echo "3. This requires modifying OpenClaw Discord configuration"

echo ""
echo "📊 **Available Minimax Models (Tested):**"
echo "-----------------------------------------"
echo "• MiniMax-M2.7 ✅ - Primary (recommended)"
echo "• MiniMax-M2.5 ✅ - Balanced"
echo "• MiniMax-M2.5-highspeed ✅ - Fast"
echo "• MiniMax-M2 ✅ - Basic"

echo ""
echo "🔧 **Environment Variables Needed:**"
echo "-----------------------------------"
echo "For Minimax to work in any channel:"
echo ""
echo "export OPENAI_API_KEY='sk-cp-mqDZwvwYG1u79lQAq_IoECIzYAvT1eBVcSOj3dIvTKcqRbRux_chEqTj1aHbvOtUCZ65CO6xYLSotXR1ocvisRzU4k6Zj1RiCpaf15ioXj5XW3DA1d8T5no'"
echo "export OPENAI_BASE_URL='https://api.minimaxi.com/v1'"
echo "export OPENAI_MODEL='MiniMax-M2.7'"

echo ""
echo "🚀 **Quick Test Command:**"
echo "--------------------------"
echo "To test Minimax right now (without Discord):"
echo ""
echo "cd /home/node/.openclaw/workspace/agents"
echo "python3 -c \"import requests; import os;"
echo "api_key = 'sk-cp-mqDZwvwYG1u79lQAq_IoECIzYAvT1eBVcSOj3dIvTKcqRbRux_chEqTj1aHbvOtUCZ65CO6xYLSotXR1ocvisRzU4k6Zj1RiCpaf15ioXj5XW3DA1d8T5no';"
echo "response = requests.post('https://api.minimaxi.com/v1/chat/completions',"
echo "  headers={'Authorization': f'Bearer {api_key}'},"
echo "  json={'model': 'MiniMax-M2.7', 'messages': ["
echo "    {'role': 'user', 'content': 'Say hello in one sentence'}"
echo "  ], 'max_tokens': 50});"
echo "print('Status:', response.status_code);"
echo "if response.status_code == 200:"
echo "  print('Response:', response.json()['choices'][0]['message']['content']);"
echo "else:"
echo "  print('Error:', response.text)\""

echo ""
echo "🎉 **Setup Summary:**"
echo "====================="
echo "✅ All configuration files created"
echo "✅ Minimax API tested and working"
echo "✅ Discord connectivity confirmed"
echo "✅ Ready for #minimax-chat channel creation"
echo ""
echo "**Next Action:** Create #minimax-chat channel in Discord"
echo "Then we can configure OpenClaw to use Minimax in that channel!"