#!/bin/bash
# Setup script for Discord channel with Minimax default

echo "🚀 Setting up Discord channel with Minimax default..."
echo "======================================================"

echo ""
echo "📋 **Step 1: Create Discord Channel**"
echo "-------------------------------------"
echo "1. Open Discord server"
echo "2. Create new text channel named: minimax-chat"
echo "3. Set channel topic: 'Minimax M2.7 AI Assistant'"
echo "4. Configure permissions as needed"

echo ""
echo "🤖 **Step 2: Configure Discord Bot**"
echo "------------------------------------"
echo "1. Ensure Discord bot is added to your server"
echo "2. Bot needs permissions:"
echo "   - Read Messages"
echo "   - Send Messages"
echo "   - Read Message History"
echo "   - Use Slash Commands"

echo ""
echo "🔧 **Step 3: Environment Setup**"
echo "--------------------------------"
echo "Set these environment variables for the bot:"
echo ""
echo "export DISCORD_BOT_TOKEN='your-discord-bot-token'"
echo "export OPENAI_API_KEY='sk-cp-mqDZwvwYG1u79lQAq_IoECIzYAvT1eBVcSOj3dIvTKcqRbRux_chEqTj1aHbvOtUCZ65CO6xYLSotXR1ocvisRzU4k6Zj1RiCpaf15ioXj5XW3DA1d8T5no'"
echo "export OPENAI_BASE_URL='https://api.minimaxi.com/v1'"
echo "export OPENAI_MODEL='MiniMax-M2.7'"

echo ""
echo "🚀 **Step 4: Run Minimax Discord Bot**"
echo "--------------------------------------"
echo "cd /home/node/.openclaw/workspace"
echo "python3 discord-minimax-bot.py"

echo ""
echo "🎯 **Step 5: Test the Setup**"
echo "-----------------------------"
echo "1. Go to #minimax-chat channel"
echo "2. Send a message like: 'Hello, are you using Minimax?'"
echo "3. Bot should respond indicating it's using Minimax M2.7"
echo "4. Try commands:"
echo "   - !help - Show all commands"
echo "   - !coding - Switch to coding agent"
echo "   - !imaging - Switch to imaging agent"
echo "   - !video - Switch to video agent"
echo "   - !status - Show current settings"

echo ""
echo "📊 **Available Agents in this Channel:**"
echo "----------------------------------------"
echo "• Default: minimax-m2.7-agent (general purpose)"
echo "• Coding: minimax-coding-agent (programming tasks)"
echo "• Imaging: minimax-imaging-agent (image analysis)"
echo "• Video: minimax-video-agent (script writing)"

echo ""
echo "💡 **Usage Examples:**"
echo "----------------------"
echo "User: Write a Python function to sort a list"
echo "Bot (after !coding): Here's a Python function..."
echo ""
echo "User: !imaging Describe what you would see in a sunset photo"
echo "Bot: I would see vibrant colors, silhouettes..."
echo ""
echo "User: !video Create a script for a 3-minute tutorial"
echo "Bot: Here's a script outline with hook, main points..."

echo ""
echo "⚠️ **Important Notes:**"
echo "----------------------"
echo "1. This channel will ONLY use Minimax models"
echo "2. Default model: MiniMax-M2.7"
echo "3. Cost: ~$0.30/$1.20 per million tokens"
echo "4. Monitor usage at: https://platform.minimaxi.com"
echo "5. Other channels continue using default models (DeepSeek)"

echo ""
echo "🔧 **Configuration Files Created:**"
echo "----------------------------------"
echo "1. discord-minimax-channel-config.json - Channel settings"
echo "2. discord-minimax-bot.py - Bot implementation"
echo "3. This setup script"

echo ""
echo "🎉 **Setup Complete!**"
echo "======================"
echo "Your Discord channel is now configured to use Minimax by default."
echo "Other channels remain unchanged (using DeepSeek/Aliyun)."
echo ""
echo "Next: Run the bot with your Discord token!"